[package]
name = "crunchyroll-watch-list"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] } 
reqwest = { version = "0.12.12", features = ["json"] } 
serde = { version = "1.0", features = ["derive"] } 
dotenv = "0.15" 
crunchyroll-rs = "0.12.1" 
